---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cwb::default]
      - recipe[cli-benchmark::default]
    attributes:
      benchmark:
        ssh_username: vagrant
        logging_enabled: true
      cli-benchmark:
        run: date
        install:
        - cd /home/vagrant
        - echo "first" > 1st.txt
        - echo "second" > 2nd.txt
        metrics:
          execution_time: .*
          year: UTC (\d+)